### ISSUE TITLE
Releasing v. 1.0.5 of Kubernetes Maven Plugin to Maven Central

### ISSUE THREAD

**Issue by ideas-into-software** [deanjameseverett/maven-plugin-k8#6]
This is a follow up to email exchange with Philip regarding releasing v. 1.0.5 of Kubernetes Maven Plugin to Maven Central (https://mvnrepository.com/artifact/com.github.deanjameseverett/k8-maven-plugin).

This is currently a **blocker**, both in terms of using latest version of Kubernetes Maven Plugin in projects' builds, since it has to be compiled and installed manually into local repositories, in addition to having the ability to push new releases with no hassle.

Currently only Dean's account (_gracewell_) is added @ Sonatype to the already authorized 'com.github.deanjameseverett' group ID (https://issues.sonatype.org/browse/OSSRH-33891), hence no other Sonatype account is able to push this new release, which is exactly the error Philip is getting @ https://travis-ci.com/phillip-kruger/k8-maven-plugin

Solution is to: 

- either add these additional usernames @ Sonatype (Philip's, perhaps mine as well) - but GitHub project collaborator role is required as well and currently only Philip has such, or 

- have Dean find few minutes time to push this new release himself.

We solve this problem now and we can easily deploy new features / fixes, and people interested in using this plugin will be able to simply reference these new versions in their build without having to install manually.

**Comment by phillip-kruger** [comment]
@deanjameseverett please help!!

**Comment by deanjameseverett** [comment]
Hi All

Michal I did ask that you be added to the repository and this was done.
I have tried to publish but I'am getting the following errors

Event: Failed: Repository Writable
Wednesday, June 05, 2019 12:30:30 SAST (GMT+0200)
typeId RepositoryWritePolicy
failureMessage Artifact updating: Repository ='releases:Releases' does not
allow updating
artifact='/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5-sources.jar'
failureMessage Artifact updating: Repository ='releases:Releases' does not
allow updating
artifact='/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5.jar'
failureMessage Artifact updating: Repository ='releases:Releases' does not
allow updating
artifact='/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5-javadoc.jar'
failureMessage Artifact updating: Repository ='releases:Releases' does not
allow updating
artifact='/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5.pom'

Have opened ticket for resolution will feedback once they have processed it.

**Comment by phillip-kruger** [comment]
You might have to version up

**Comment by phillip-kruger** [comment]
So 1.0.6. It might be that the parent pom got into Oss nexux but the rest failed. Maven central only allow one time release of a version. If you release again it has to have a new version number ( with the exception of snapshot)

**Comment by deanjameseverett** [comment]
Ok trying that

**Comment by deanjameseverett** [comment]
I bumped the version 1.0.6 but it still failed it's still looking to
publish 1.0.5.

Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6-javadoc.jar.asc
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6-javadoc.jar.asc
(488 B at 242 B/s)
Downloading from ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/maven-metadata.xml
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/maven-metadata.xml
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/maven-metadata.xml
(322 B at 94 B/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6.pom.asc
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6.pom.asc
(488 B at 850 B/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5-javadoc.jar
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5-javadoc.jar
(136 kB at 53 kB/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6-sources.jar
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6-sources.jar
(21 kB at 12 kB/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5.jar
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5.jar
(41 kB at 24 kB/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5.pom
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5.pom
(8.1 kB at 4.7 kB/s)
Downloading from ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/maven-metadata.xml
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/maven-metadata.xml
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/maven-metadata.xml
(222 B at 71 B/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6.jar.asc
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6.jar.asc
(488 B at 859 B/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6.jar
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6.jar
(41 kB at 21 kB/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6.pom
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6.pom
(8.1 kB at 4.7 kB/s)
Downloading from ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/maven-metadata.xml
Downloaded from ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/maven-metadata.xml
(222 B at 378 B/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/maven-metadata.xml
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/maven-metadata.xml
(222 B at 130 B/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5-javadoc.jar.asc
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5-javadoc.jar.asc
(488 B at 854 B/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6-javadoc.jar
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6-javadoc.jar
(136 kB at 68 kB/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5-sources.jar.asc
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5-sources.jar.asc
(488 B at 854 B/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5.jar.asc
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5.jar.asc
(488 B at 845 B/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5.pom.asc
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5.pom.asc
(488 B at 857 B/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6-sources.jar.asc
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.6/k8-maven-plugin-1.0.6-sources.jar.asc
(488 B at 850 B/s)
Uploading to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5-sources.jar
Uploaded to ossrh:
https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubdeanjameseverett-1023/com/github/deanjameseverett/k8-maven-plugin/1.0.5/k8-maven-plugin-1.0.5-sources.jar
(21 kB at 12 kB/s)

**Comment by phillip-kruger** [comment]
Not sure why this happens, can we not somehow tell not to publish the older versions ?

**Comment by deanjameseverett** [comment]
HI All

Finally it deployed it took a couple of runs.
But 1.0.6 is now released.

Michal you should be good to go.

Regards
Dean James-Everett

**Comment by phillip-kruger** [comment]
Thanks Dean !!

**Comment by phillip-kruger** [comment]
I am closing this issue. The new version is available in maven central:
https://search.maven.org/artifact/com.github.deanjameseverett/k8-maven-plugin/1.0.6/maven-plugin

**Comment by ideas-into-software** [comment]
Great! 

Dean, to clarify - it's not for myself; I mentioned to Philip primary reason is the article detailing entire automation pipeline involving this plugin being published, so having latest release of this plugin available in Maven Repository is important.

One thing I noticed is that Philip is referring to version 1.0.6 in his most recent comment (https://search.maven.org/artifact/com.github.deanjameseverett/k8-maven-plugin/1.0.6/maven-plugin) - did you make any additional changes to v.1.0.6 that it had to be released instead of v.1.0.5? 

In Maven repository I see v.1.0.5 as being most recent: https://mvnrepository.com/artifact/com.github.deanjameseverett/k8-maven-plugin, dated May 29th - is this version also valid?

Thank you for your help.
